.github/workflows/check-pull-request.yml
Dockerfile

As our solution template currently references version 6.9.0, we need to ensure the same version of the CLI tools are installed when building the container.
As now main cannot build and push.
~Do we have the ability to run a `docker build` as part of the PR checks?~
A check PR docker build step has now been included in our PR workflow.

Anchor to version 6.9.0 otherwise version 7 is installed

---

Dockerfile
Makefile

This was missed in the previous package update PR https://github.com/DEFRA/pha-import-notifications/pull/17.

Drop old Swashbuckle CLI version now that we're on version 7

---

src/Api/SwashbuckleFilters/AddSwashbuckleHeaders.cs

This parameter was not being used and caused SonarCloud to throw a warning.

PHAIN-33: Fix SonarCloud warning

---

src/Contracts/CommodityRiskResult.g.cs
src/Contracts/ComplementParameterSet.g.cs
src/Contracts/ControlAuthority.g.cs
src/Contracts/ImportNotification.g.cs
src/Contracts/PartOne.g.cs
src/Contracts/PartTwo.g.cs
src/Contracts/VeterinaryInformation.g.cs
tests/Api.IntegrationTests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
tools/SchemaToCSharp/Ignored.cs
tools/SchemaToCSharp/Meta.cs
tools/SchemaToCSharp/Program.cs

This PR adds the ability to ignore fields during our schema generation.
It also allows description text to be overridden for fields.
The main point of discussion is the `CreatedSource` and `UpdatedSource` fields on an `ImportNotification`. There are additional `Created` and `Updated` fields from BTMS. As it stands, all 4 fields are being returned. We most likely want one of the pairs but this could involve field mapping, which should be discussed first.
I have also removed the auto exclusion of a field if it starts with an underscore. And replaced it with explicit ignores so we have the fields if we need them but they are not included in our public response.

Ignore fields from BTMS that we do not want to expose in our PHA contract

---

src/Api/Configuration/BtmsOptions.cs
src/Api/JsonApi/ServiceCollectionExtensions.cs
src/Api/Program.cs
src/Api/appsettings.json
tests/Api.Tests/Configuration/BtmsOptionsTests.cs
tests/Api.Tests/JsonApi/ServiceCollectionExtensionsTests.cs

BTMS currently authenticates via basic auth.
This change adds a basic auth header to all requests, configured by environment variables.

PHAIN-80: Add Basic auth for BTMS

---

src/Api/Api.csproj
src/Api/Configuration/BtmsOptions.cs
src/Api/JsonApi/SingleOrManyDataConverterFactory.cs
src/Api/Program.cs
src/Api/Services/Btms/StubBtmsService.cs
src/Api/Services/Btms/WireMockBtmsService.cs
src/Api/appsettings.Development.json
src/Api/appsettings.json
tests/Api.IntegrationTests/Endpoints/EndpointTestBase.cs

This adds WireMock for stubbing BTMS responses which is enabled via the Btms_StubEnabled feature flag.
It is currently disabled for the integration tests until we've added the stubs for them to pass.

PHAIN-38: Add WireMock for stubbing BTMS

---

src/Api/Configuration/BtmsOptions.cs
src/Api/Services/Btms/WireMockBtmsService.cs
tests/Api.IntegrationTests/Endpoints/EndpointTestBase.cs

When running the integration tests, they attempt to start multiple instances of WireMock which fail because they are trying to use the same port.

PHAIN-38: Allocate a random port for WireMock

---

.vacuum.yml
Dockerfile
Makefile
src/Api/Authentication/BasicAuthenticationHandler.cs
src/Api/Configuration/BasicAuthOptions.cs
src/Api/Configuration/BasicAuthOptionsValidator.cs
src/Api/Configuration/BtmsOptions.cs
src/Api/Endpoints/ImportNotifications/EndpointRouteBuilderExtensions.cs
src/Api/Extensions/BasicAuthenticationExtensions.cs
src/Api/Helpers/BasicAuthHelper.cs
src/Api/Program.cs
src/Api/appsettings.Development.json
src/Api/appsettings.IntegrationTests.json
tests/Api.IntegrationTests/Endpoints/EndpointTestBase.cs
tests/Api.IntegrationTests/Endpoints/ImportNotifications/GetTests.cs
tests/Api.IntegrationTests/Endpoints/ImportNotifications/GetUpdatedTests.cs
tests/Api.IntegrationTests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
tests/Api.Tests/Authentication/BasicAuthenticationHandlerTests.cs
tests/Api.Tests/Configuration/BasicAuthOptionsValidatorTests.cs
tests/Api.Tests/Helpers/BasicAuthHelperTests.cs

We're going to use Basic Auth until our auth provider is ready.
This change adds it and updates the OpenAPI spec to require the Authorization header.

PHAIN-99: Add Basic Authentication

---

Dockerfile
Makefile

The Dockerfile was installing the Swagger CLI globally, ignoring the version that is set in the tool manifest.
This change updates it to install from the manifest and then use it.

BAU: Use the dotnet tool version of the Swagger CLI

---

src/Api/Configuration/BtmsOptions.cs
src/Api/Endpoints/ImportNotifications/EndpointRouteBuilderExtensions.cs
src/Api/Endpoints/ImportNotifications/UpdatedImportNotificationRequest.cs
src/Api/JsonApi/ComparisonOperator.cs
src/Api/Services/Btms/BtmsService.cs
src/Api/Services/Btms/IBtmsService.cs
tests/Api.IntegrationTests/Endpoints/ImportNotifications/GetTests.cs
tests/Api.IntegrationTests/Endpoints/ImportNotifications/GetUpdatedTests.cs
tests/Api.IntegrationTests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
tests/Api.Tests/JsonApi/FilterTests.cs
tests/Api.Tests/Services/Btms/BtmsServiceTests.cs
tests/Testing/Endpoints.cs

Main point to note is that we filter BTMS by greater than or equal to the from date we are given and then less than the to date we are given. This will allow call ranges from our consumers to succeed without us dropping any data.
~Should we update the open API docs to indicate this behaviour?~ Agreed that we should update and a change has been included.
Also page PageSize configurable when calling BTMS for updates. Naming is generic but it's only used when retrieving updates. If we ever need multiple page size values then we can implement it then.

Add from and to filters when looking for import notification updates

---

src/Api/appsettings.cdp.Perf-test.json
src/Api/appsettings.cdp.Test.json

This assumes we want to use the BTMS stub in CDP perf-test and test environments.

Set BTMS base URL as WireMock stub for perf-test and test

---

src/Api/appsettings.cdp.Ext-test.json

This config sets the API to use the stub in external test.

Add ext-test environment config

---

src/Api/Program.cs
src/Api/appsettings.IntegrationTests.json
src/Api/appsettings.cdp.Ext-test.json
src/Api/appsettings.cdp.Prod.json
tests/Api.IntegrationTests/Endpoints/EndpointTestBase.cs
tests/Api.IntegrationTests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
tests/Api.IntegrationTests/TestWebApplicationFactory.cs

This approach was chosen as the host values don't map to CDP environments and there will be load balancers obscuring being to work it our automatically unless we start messing with HTTP headers so for now, this is kept simple.
Also worth noting that all lower CDP environments will still use localhost.

Set the open API server host for prod and external test

---

src/Api/Utils/Logging/CdpLogging.cs

The ECS / Serilog guidance looks wrong to me. This approach seems safer.
The `.Configuration.Get<T>()` frameworks methods are for configuration and not instantiation of the `HttpClientAccessor`.

Use correct Serilog enrichment / configuration

---

src/Api/Authentication/BasicAuthenticationHandler.cs
src/Api/Authentication/PhaClaimTypes.cs
src/Api/Configuration/AclOptions.cs
src/Api/Program.cs
src/Api/Properties/launchSettings.json
src/Api/appsettings.Development.json
src/Api/appsettings.IntegrationTests.json
tests/Api.Tests/Authentication/BasicAuthenticationHandlerTests.cs

A client only has access to certain BCPs.
This identifies the client set by config from environment variables and adds the BCP claims to the AuthenticationTicket, which can be later used to authorise requests.

PHAIN-41: Add BCPs to authenticated user claims

---

src/BtmsStub/Scenarios/btms-import-notification-updates.json
tests/Api.Tests/Services/Btms/BtmsServiceTests.GetImportNotificationUpdates_WhenOk_ShouldSucceed.verified.txt

This will allow the updates response to be followed and some of the CHED reference numbers can then be retrieved in a subsequent request.

Replace stubbed updates response with several CHEDs that will return data as they are also stubbed

---

src/Api/appsettings.IntegrationTests.json
src/BtmsStub/Scenarios/btms-import-notification-single-CHEDA.GB.2024.4792831.json
src/BtmsStub/Scenarios/btms-import-notification-single-CHEDA.GB.2024.5129502.json
src/BtmsStub/Scenarios/btms-import-notification-single-CHEDP.GB.2024.4144842.json
src/BtmsStub/Scenarios/btms-import-notification-single-CHEDPP.GB.2024.3726460.json
tests/Api.IntegrationTests/Endpoints/ImportNotifications/GetTests.Get_WhenFound_ShouldSucceed.verified.json
tests/Api.Tests/Services/Btms/BtmsServiceTests.GetImportNotification_WhenOk_ShouldSucceed.verified.txt
tests/Api.Tests/Services/Btms/BtmsServiceTests.GetImportNotification_WithMovements_WhenOk_ShouldSucceed.verified.txt

Using the river_tees_pha client will allow the stubbed data in ext-test to return when requested.

Set stubbed response BCP to be GBTEEP1 so river_tees_pha can be used

---

src/Api/appsettings.cdp.test.json

We are changing to use the stub service rather than the hosted version.

PHAIN-104: Disable stub for test

---

.github/workflows/check-pull-request.yml

This adds Trivy as part of the build checks to scan a container for vulnerabilities.

PHAIN-42: Scan container for vulnerabilities

---

.vacuum.yml

We are no longer using basic auth.

PHAIN-42: Remove basic auth rule exemption

---

README.md

This change adds some instructions to the README for using a real BTMS instance to develop against.

PHAIN-133: Add instructions for querying a deployed BTMS instance

---

README.md

BTMS now publishes a OpenAPI spec as an artifact during each merge to main which means we no longer need to generate it ourselves.

PHAIN-133: Update README around generating models from BTMS

---

Defra.PhaImportNotifications.sln.DotSettings
src/Contracts/ImportNotification.cs
tests/Api.IntegrationTests/Endpoints/ImportNotifications/GetTests.Get_AllStubs_ShouldSucceed_chedReferenceNumber=CHEDD.GB.2024.5019877.verified.json
tests/Api.IntegrationTests/Endpoints/ImportNotifications/GetTests.Get_AllStubs_ShouldSucceed_chedReferenceNumber=CHEDD.GB.2024.5118377.verified.json
tests/Api.IntegrationTests/Endpoints/ImportNotifications/GetTests.Get_AllStubs_ShouldSucceed_chedReferenceNumber=CHEDP.GB.2024.5253621.verified.json
tests/Api.IntegrationTests/Endpoints/ImportNotifications/GetTests.Get_AllStubs_ShouldSucceed_chedReferenceNumber=CHEDP.GB.2024.5328437.verified.json
tests/Api.IntegrationTests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt

Previously, finalisations were returned as an array with property name `finalisation`, which suggested a single value. It can be more than one so make the property name plural.

Change property name to plural as it's an array

---

tests/Api.IntegrationTests/Endpoints/ImportNotifications/GetTests.cs

[PHAIN-159](https://eaflood.atlassian.net/browse/PHAIN-159)
Adds a test to ensure that the Get individual notification endpoint works when the user is authorised to access all BCPs (i.e. is the FSA user)
[PHAIN-159]: https://eaflood.atlassian.net/browse/PHAIN-159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PHAIN-159 Add test for Get endpoint for FSA user
